#!/bin/bash


function jvalPluginGetDependencies() {
    echo "python python:yaml"
}


function jvalPluginGetTargetFiles() {
    targetType="$1"
    targetPath="$2"

    cd "$targetPath"

    if [[ $targetType == "--dir" ]]; then
        targetFiles=$(find . -type f -name '*.yml' 2>/dev/null | cut -c3-)
    elif [[ $1 == "--gitrepo" ]]; then
        targetFiles=$(git diff --cached --name-only --diff-filter=AM -- \*.yml)
    fi

    echo "$targetFiles"
}


function jvalPluginValidateFile() {
    targetFile="$1"

    py="import yaml, sys
try:
    src = open(sys.argv[1], 'r').read() + '\n'; yaml.safe_load(src)
except yaml.YAMLError as e:
    raise e";

    result=$(python -c "$py" "$entry" 2>&1)

    if [[ $? == 0 ]]; then
        exit 0
    else
        echo "$result" | sed 's/^/  /'
        exit 1
    fi
}
