#!/bin/bash


# Set variables
dependencylist="xmllint"


# Report dependencies
[[ $1 == "--dependencies" ]] && { printf "$dependencylist\n"; exit 0; }


# Get files
cd "$2"
if [[ $1 == "--dir" ]]; then
    files=$(find . -readable -type f -name '*.xml' 2> /dev/null | cut -c3-)
elif [[ $1n == "--gitrepo" ]]; then
    files=$(git diff --cached --name-only --diff-filter=AM -- \*.xml)
fi


# Validate files
if [[ ! -z $files ]]; then
    printf "\nValidating XML documents:\n"
    readarray -t files <<< "$(echo "$files" | sort)"

    for entry in "${files[@]}"; do
        printf "  * $entry... "
        out=$(xmllint --noout "$entry" 2>&1)

        if [[ $? == 0 ]]; then
            printf "\e[32mValid\e[39m\n"
        else
            printf "\n\n\e[94m$(echo "$out" | sed 's/^/  /')\e[39m\n"
            exit 1
        fi
    done
fi


# All good, exit with status 0
exit 0
