#!/bin/bash


function jvalPluginGetDependencies() {
    echo "ansible-playbook"
}


function jvalPluginGetTargetFiles() {
    targetType="$1"
    targetPath="$2"

    cd "$targetPath"

    if [[ $targetType == "dir" ]]; then
        targetFiles=$(grep -rsI --files-with-matches --include='*.yml' '\- hosts:' 2>/dev/null)
    elif [[ $targetType == "gitrepo" ]]; then
        targetFiles=$(git diff --cached --name-only --diff-filter=AM -- \*.yml)
        [[ ! -z $targetFiles ]] && targetFiles=$(grep -rsI --files-with-matches --include='*.yml' '\- hosts:' 2>/dev/null)
    fi

    echo "$targetFiles"
}


function jvalPluginValidateFile() {
    targetFile="$1"

    result=$(ansible-playbook --syntax-check "$targetFile" 2>&1)

    if [[ $? == 0 ]]; then
        exit 0
    else
        echo "$result" | sed '/^$/{n;/^$/d}'
        exit 1
    fi
}
