#!/bin/bash


function jvalPluginGetDependencies() {
    echo "bash"
}


function jvalPluginGetTargetFiles() {
    targetType="$1"
    targetPath="$2"

    cd "$targetPath"

    if [[ $targetType == "--dir" ]]; then
        targetFiles=$(grep -rsI --files-with-matches --exclude-dir=.git -m1 -E '^#![ ]?/bin/(sh|bash)' 2> /dev/null | while read line; do awk 'NR==1&&/^#![ ]?\/bin\/(sh|bash)/{ print FILENAME }' "$line"; done)
    elif [[ $targetType == "--gitrepo" ]]; then
        targetFiles=$(git diff --cached --name-only --diff-filter=AM | xargs grep -I --files-with-matches -E '^#![ ]?/bin/(sh|bash)' 2>/dev/null)
    fi

    echo "$targetFiles"
}


function jvalPluginValidateFile() {
    targetFile="$1"

    result=$(bash -n "$targetFile" 2>&1)

    if [[ $? == 0 ]]; then
        exit 0
    else
        echo "$result" | sed 's/^/  /'
        exit 1
    fi
}
