#!/bin/bash


function jvalPluginGetDependencies() {
    echo "xmllint"
}


function jvalPluginGetTargetFiles() {
    targetType="$1"
    targetPath="$2"

    cd "$targetPath"

    if [[ $targetType == "dir" ]]; then
        targetFiles=$(find . -readable -type f -name '*.xml' 2>/dev/null | cut -c3-)
    elif [[ $targetType == "gitrepo" ]]; then
        targetFiles=$(git diff --cached --name-only --diff-filter=AM -- \*.xml)
    fi

    echo "$targetFiles"
}


function jvalPluginValidateFile() {
    targetFile="$1"

    result=$(xmllint --noout "$entry" 2>&1)

    if [[ $? == 0 ]]; then
        exit 0
    else
        echo "$result"
        exit 1
    fi
}
