#!/bin/bash


function jvalPluginGetDependencies() {
    echo "python"
}


function jvalPluginGetTargetFiles() {
    targetType="$1"
    targetPath="$2"

    cd "$targetPath"

    if [[ $targetType == "--dir" ]]; then
        targetFiles=$(find . -readable -type f -name '*.py' 2>/dev/null | cut -c3-)
    elif [[ $1 == "--gitrepo" ]]; then
        targetFiles=$(git diff --cached --name-only --diff-filter=AM -- \*.py)
    fi

    echo "$targetFiles"
}


function jvalPluginValidateFile() {
    targetFile="$1"

    result=$(python -c "import sys; src = open(sys.argv[1], 'r').read() + '\n'; compile(src, sys.argv[1], 'exec')" "$targetFile" 2>&1)

    if [[ $? == 0 ]]; then
        exit 0
    else
        echo "$result" | tail -n +3 | sed 's/^  //'
        exit 1
    fi
}
